services:
  - type: web
    name: nrx-store-backend
    env: python
    runtime: python-3.11.0
    region: singapore
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    healthCheckPath: /health
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: False
